Django/myblog/blog/urls.py
#! /usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>\d+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>\d+)$', views.edit_page, name="edit_page2"),
    url(r'^edit/action/$', views.edit_action, name="edit_action"),
    url(r'^$', views.index),
]

Django/myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# import blog.views as bv

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^index/', bv.index),
    
    # 为了防止该文件越积越大的问题，建议使用include添加外部urls配置文件的方式
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

Django/myblog/blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32, default="Title")
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

Django/myblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models

# Create your views here.
# 每一个响应对应一个函数，函数必须返回一个响应
# 函数必须存在一个参数，一般约定为request
# 每个函数对应一个url
def index(request):
    # return HttpResponse("Hello world!")
    # 第三个参数为传给前端页面的数值
    
    # 获取主键为1的对象
    # article = models.Article.objects.get(pk = 1)
    # return render(request, 'blog/index.html', {'hello': 'Hello Blog!','article' : article})
    
    # 获取所有的article列表
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles' : articles})
    
    
def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article':article})

def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article':article})

def edit_action(request):
    # title = request.POST['title']
    # 为了防止request请求中没有title的请求参数，建议使用以下代码
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        # 返回主页
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles' : articles})
    
    else:
        article = models.Article.objects.get(pk = article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/article_page.html', {'article':article})
    

Django/myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{ article.title }}</h1>
	<br/>
	<h3>{{ article.content }}</h3>
	<br/><br/>
	<a href="{% url 'blog:edit_page2' article.id %}">修改文章</a>
</body>
</html>

Django/myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<form action="{% url 'blog:edit_action' %}" method="post">
		{% csrf_token %}<!-- 凡是使用post提交的表单，都需要该行 -->
		
		{% if article %}
		<input type="hidden" name="article_id" value="{{ article.id }}" />
		<label>文件标题<input name="title" value="{{ article.title}}"/></label>
		<label>文件内容<input name="content" value="{{ article.content }}"/></label>
		{% else %}
		<input type="hidden" name="article_id" value="0" />
		<label>文件标题<input name="title"/></label>
		<label>文件内容<input name="content"/></label>
		{% endif %}
		<input type="submit" value="提交" />
	</form>
</body>
</html>

Django/myblog/blog/templates/blog/edit_page2.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<form action="{% url 'blog:edit_action' %}" method="post">
		{% csrf_token %}<!-- 凡是使用post提交的表单，都需要该行 -->
		
		<!-- 使用templates过滤器 -->
		<input type="hidden" name="article_id" value="{{ article.id | default: '0'}}" />
		<label>文件标题<input name="title" value="{{ article.title}}"/></label>
		<label>文件内容<input name="content" value="{{ article.content }}"/></label>
		<input type="submit" value="提交" />
	</form>
</body>
</html>

Django/myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<!-- 
	<h1 style="color:red;">Hello Django</h1>
	<hr/>
	<h1 style="color:red;">{{ hello }}</h1>
	<hr/>
	<h1 style="color:red;">{{ article.title }}</h1>
	{{ article.content }}
	 -->
	 <h2><a href="{% url 'blog:edit_page2' 0 %}">新文章</a></h2>
	 {%	for article in articles %}
	 <!-- 
	 	template中可以使用类似"{% url 'blog:article_page' article.id %}"
	 	第一部分: url为固定写法,
	 	第二部分: 'app-name:url-name'
	 	app-name为主工程的urls中include的namespace
	 	url-nane为该应用的urls中url的name
	 	第三部分: param为传递给url的参数
	  -->
	 <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
	 <br/>
	 {% endfor %}
</body>
</html>